# Very simple + crude way to build an nrf connect sdk based project

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Zephyr SDK
        run: |
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_linux-x86_64_minimal.tar.xz
          tar xf zephyr-sdk-0.16.4_linux-x86_64_minimal.tar.xz -C ~/
          ~/zephyr-sdk-0.16.4/setup.sh -c -t arm-zephyr-eabi

      - name: Install Dependencies + West
        run: |
          sudo apt install --no-install-recommends git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
            make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1

          pip3 install west

      - name: Initialize Zephyr Workspace
        run: |
          # hope there's a directory above us lol
          PROJDIR_=$(basename ${PWD})
          cd ..
          west init -l ${PROJDIR_}
          west update --narrow -o=--depth=1
          pip3 install -r zephyr/scripts/requirements.txt
          west build -b nrf7002dk_nrf5340_cpuapp --pristine=always ${PROJDIR_} \
            -- \
            -DCONFIG_MEMFAULT_NCS_PROJECT_KEY=\"1234\"
